[package]
name = "syslog_loose"
version = "0.1.0"
authors = ["Stephen Wakely <fungus.humungus@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5"
chrono = "0.4"

[dev-dependencies]
criterion = "0.3.0"
syslog_rfc5424 = "0.6.1"
quickcheck = "0.9.0"

[[example]]
name = "server"

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
